# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Dev Deploy'
    jobs:
      - job: Devjob
        steps:
          - bash: echo Devjob
 
  - stage: 'QA Deploy'
    jobs:
      - job: QAJob
        steps:
          - bash: echo QAJob
  - stage: "Prod Deploy"
    jobs:
      - job: Prodjob
        steps:
          - bash: echo Prodjob



